### PR TITLE
Allow Laravel 6.x and 7.x in composer.json

### PR DESCRIPTION
**Pull request by abronin**
Please, help with Issue #30 

No additional constraints, no breaking changes. This 100% safe change will allow more people to use your package directly (not making forks just because of this problem).

### CODE REVIEW

**Comment by Parziphal** [comment]
Sorry I didn't see this earlier. Thank you~

**Comment by abronin** [comment]
@Parziphal Thank you!

**Comment by abronin** [comment]
If you can tag this as a new version, it will allow us to use your package in our projects. It will be great help for folks like me (I saw some here in github) who use their forks in production because of we need the Laravel 6.x or 7.x support.

**Comment by Parziphal** [comment]
Oh yeah I forgot about tagging. I've been away for too long.
I created it through web interface, I hope it just works as expected. If you need me to do anything else, please let me know.

**Comment by abronin** [comment]
Thank you!
One more thing) I mentioned you added wrong release note "Allow to Laravel 5.6 and 5.7."
It should be "Allow to Laravel 6.x and 7.x."

**Comment by Parziphal** [comment]
Lol, my bad, I corrected it. Thank you~

**Pull request merged**
